### ISSUE TITLE
Rule kms::DisabledKey is not available in reporter

### ISSUE THREAD

**Issue by izzatzaki** [aws-samples/service-screener-v2#69]
Ran the report from central account with cross account enabled. The script stopped when this error occurred. Region is ap-southeast-1.

```
[__!! WARNING !!__] Rule kms::DisabledKey is not available in reporter, please submit an issue to github.
Traceback (most recent call last):
  File "/home/cloudshell-user/service-screener-v2/main.py", line 274, in <module>
    Screener.generateScreenerOutput(runmode, contexts, hasGlobal, regions, uploadToS3, bucket)
  File "/home/cloudshell-user/service-screener-v2/Screener.py", line 171, in generateScreenerOutput
    reporter.process(resultSets).getSummary().getDetails()
  File "/home/cloudshell-user/service-screener-v2/services/Reporter.py", line 186, in getSummary
    dashboard['CATEGORY'][region][mainCategory][critical] += itemSize
KeyError: 'X'
```

Please assist.

**Comment by kuettai** [comment]
Looking into this within next 48 hours

**Comment by izzatzaki** [comment]
Hi @kuettai 

I ran the screener again and received the following error:

`RdspageBuilder class not found, using default pageBuilder
EfspageBuilder class not found, using default pageBuilder
S3pageBuilder class not found, using default pageBuilder
Ec2pageBuilder class not found, using default pageBuilder
CloudfrontpageBuilder class not found, using default pageBuilder
ElasticachepageBuilder class not found, using default pageBuilder
LambdapageBuilder class not found, using default pageBuilder
CloudtrailpageBuilder class not found, using default pageBuilder
OpensearchpageBuilder class not found, using default pageBuilder
[__!! WARNING !!__] Rule kms::DisabledKey available in reporter, but missing ref, please submit an issue to github.
KmspageBuilder class not found, using default pageBuilder
Traceback (most recent call last):
  File "/home/ec2-user/service-screener-v2/main.py", line 273, in <module>
    Screener.generateScreenerOutput(runmode, contexts, hasGlobal, regions, uploadToS3, bucket)
  File "/home/ec2-user/service-screener-v2/Screener.py", line 178, in generateScreenerOutput
    pb.buildPage()
  File "/home/ec2-user/service-screener-v2/services/PageBuilder.py", line 68, in buildPage
    output.append(self.buildContentSummary())
  File "/home/ec2-user/service-screener-v2/services/PageBuilder.py", line 89, in buildContentSummary
    return getattr(self, method)()
  File "/home/ec2-user/service-screener-v2/services/PageBuilder.py", line 650, in buildContentSummary_default
    body = self.generateSummaryCardContent(attrs)
  File "/home/ec2-user/service-screener-v2/services/PageBuilder.py", line 202, in generateSummaryCardContent
    if summary['__links']:
KeyError: '__links'`

I've pull from main branch (latest) before testing. Kindly assist.
