### ISSUE TITLE
screener-v2 throws error when inspecting certain cloudfront distribution, S3 bucket

### ISSUE THREAD

**Issue by vfchoo** [aws-samples/service-screener-v2#7]
**Describe the bug**
screener-v2 throws error when inspecting certain cloudfront distribution, S3 bucket

**To Reproduce**
 - Run main.py and specify any region

**Error**
`
... (S3Bucket) inspecting XXXXX
Traceback (most recent call last):
  File "/home/cloudshell-user/screenerv2/service-screener-v2/services/Evaluator.py", line 27, in run
    getattr(self, method)()
  File "/home/cloudshell-user/screenerv2/service-screener-v2/services/lambda_/drivers/LambdaCommon.py", line 180, in _check_runtime
    runtime = self.lambda_['Runtime']
KeyError: 'Runtime
`

`
... (CloudFront::Distribution) inspecting XXX
Traceback (most recent call last):
  File "/home/cloudshell-user/screenerv2/service-screener-v2/services/Evaluator.py", line 27, in run
    getattr(self, method)()
  File "/home/cloudshell-user/screenerv2/service-screener-v2/services/lambda_/drivers/LambdaCommon.py", line 180, in _check_runtime
    runtime = self.lambda_['Runtime']
KeyError: 'Runtime'
`

**AWS CloudShell (please complete the following information):**
 - Region: ap-southeast-1

**Comment by kuettai** [comment]
It seems like the error related to self.lambda_['Runtime'], do you happen to have the output.zip with you? Inside should have a file name: "error.txt". Can you paste the output of the error.txt here?

**Comment by vfchoopulsifi** [comment]
Unfortunately unable to as the script terminated with error after inspecting the resources. The error is in this issue #8

**Comment by cykhoo0108** [comment]
Will try to simulate and fix this issue
