### ISSUE TITLE
Multiprocessing error

### ISSUE THREAD

**Issue by sheshankgujjari** [aws-samples/service-screener-v2#73]
**Describe the bug**
Multiprocessing error

**To Reproduce**
1. Clone Repo
2. Setup Alias
3. Run command

**Expected behavior**
Execute without any errors

**AWS CloudShell (please complete the following information):**
 - Region:  us-east-1

**Additional context**
[__!! WARNING !!__] Unable to describe the CUR report. It is likely that this account is part of AWS Organizations
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/cloudshell-user/service-screener-v2/Screener.py", line 77, in scanByService
    contexts[service[0]][region] = serv.advise()
  File "/home/cloudshell-user/service-screener-v2/services/rds/Rds.py", line 159, in advise
    self.getSecrets()
  File "/home/cloudshell-user/service-screener-v2/services/rds/Rds.py", line 88, in getSecrets
    self.registerSecrets(results)
  File "/home/cloudshell-user/service-screener-v2/services/rds/Rds.py", line 101, in registerSecrets
    if self.resourceHasTags(secret['Tags']) == False:
KeyError: 'Tags'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cloudshell-user/service-screener-v2/main.py", line 194, in <module>
    pool.starmap(Screener.scanByService, input_ranges)
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'Tags'

**Comment by sheshankgujjari** [comment]
Please close the issue, when I use the parameter "--mode" there is no error.
