### ISSUE TITLE
Rule kms::DisabledKey available in reporter, but missing ref

### ISSUE THREAD

**Issue by izzatzaki** [aws-samples/service-screener-v2#78]
Hi @kuettai . Referring to issue #69 , understand that you have addressed it recently but after running the screener again, I received the following error:

`RdspageBuilder class not found, using default pageBuilder
EfspageBuilder class not found, using default pageBuilder
S3pageBuilder class not found, using default pageBuilder
Ec2pageBuilder class not found, using default pageBuilder
CloudfrontpageBuilder class not found, using default pageBuilder
ElasticachepageBuilder class not found, using default pageBuilder
LambdapageBuilder class not found, using default pageBuilder
CloudtrailpageBuilder class not found, using default pageBuilder
OpensearchpageBuilder class not found, using default pageBuilder
[__!! WARNING !!__] Rule kms::DisabledKey available in reporter, but missing ref, please submit an issue to github.
KmspageBuilder class not found, using default pageBuilder
Traceback (most recent call last):
  File "/home/ec2-user/service-screener-v2/main.py", line 273, in <module>
    Screener.generateScreenerOutput(runmode, contexts, hasGlobal, regions, uploadToS3, bucket)
  File "/home/ec2-user/service-screener-v2/Screener.py", line 178, in generateScreenerOutput
    pb.buildPage()
  File "/home/ec2-user/service-screener-v2/services/PageBuilder.py", line 68, in buildPage
    output.append(self.buildContentSummary())
  File "/home/ec2-user/service-screener-v2/services/PageBuilder.py", line 89, in buildContentSummary
    return getattr(self, method)()
  File "/home/ec2-user/service-screener-v2/services/PageBuilder.py", line 650, in buildContentSummary_default
    body = self.generateSummaryCardContent(attrs)
  File "/home/ec2-user/service-screener-v2/services/PageBuilder.py", line 202, in generateSummaryCardContent
    if summary['__links']:
KeyError: '__links'`

I've pulled from the latest main branch prior testing.  Kindly assist.

**Comment by kuettai** [comment]
Hi, thank for reporting! We run a full scan to ensure no more missing links in all the reporters. I fixed at #79 , please validate and let us know if any other errors has surfaced.

**Comment by izzatzaki** [comment]
Hi @kuettai . Tested and no error returned.

Looks good for now.

Thank you.
