### ISSUE TITLE
EFS Policy Not Found Error

### ISSUE THREAD

**Issue by crazykit93** [aws-samples/service-screener-v2#95]
**Describe the bug**
Error prompt when inspecting EFS

**Expected behavior**
EFS with disabled "Automatic backups", thus "policy not found" prompted.

**Screenshot**
![image](https://github.com/aws-samples/service-screener-v2/assets/73178157/782fa1b7-972f-4a9d-bf17-d6506bf17fbc)

**Error Captured"
... (EFS) inspecting fs-090404821061821eb
PolicyNotFound None
Traceback (most recent call last):
  File "/home/cloudshell-user/service-screener-v2/services/Evaluator.py", line 46, in run
    getattr(self, method)()
  File "/home/cloudshell-user/service-screener-v2/services/efs/drivers/EfsDriver.py", line 32, in _checkBackupPolicy
    backup = self.efs_client.describe_backup_policy(
  File "/home/cloudshell-user/lib64/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/cloudshell-user/lib64/python3.9/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.PolicyNotFound: An error occurred (PolicyNotFound) when calling the DescribeBackupPolicy operation: None

**Comment by kuettai** [comment]
Close this issue. It fixed in #103
